{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Memory_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPU_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(all[1m])", "legendFormat": "__auto" },
    { "expr": "rate(delete[1m])", "legendFormat": "__auto" },
    { "expr": "rate(get[1m])", "legendFormat": "__auto" },
    { "expr": "rate(post[1m])", "legendFormat": "__auto" },
    { "expr": "rate(put[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}